# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-18 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel', '0002_attractions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturant_name', models.CharField(max_length=30)),
                ('resturant_image', models.ImageField(upload_to='resturant_image/%Y/%m/%d')),
                ('resturant_rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_name', models.CharField(max_length=30)),
                ('travel_image', models.ImageField(upload_to='travel_image/%Y/%m/%d')),
                ('travel_rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
