# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-18 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel', '0003_resturants_travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='travel_rating',
        ),
    ]
