# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-19 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_travel', '0007_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
